import React, { useEffect, useState } from 'react';
import { getSupabase } from './client';

export default function TestSupabase() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const run = async () => {
      setLoading(true);
      setError(null);
      try {
        const supabase = getSupabase();
        // Try a lightweight read from the kv_store table that exists in the autogenerated file.
        const { data, error } = await supabase.from('kv_store_bd8c6dc5').select('*').limit(5);
        if (error) {
          setError(error.message);
        } else {
          setResult(data);
        }
      } catch (err: any) {
        setError(err.message ?? String(err));
      } finally {
        setLoading(false);
      }
    };
    run();
  }, []);

  return (
    <div className="p-4 bg-white shadow rounded max-w-3xl w-full">
      <h2 className="text-lg font-semibold">Supabase Test</h2>
      <p className="text-sm text-muted-foreground mb-2">This runs a small query against your Supabase project using VITE env vars.</p>
      {loading && <div>Loading…</div>}
      {error && <div className="text-red-600">Error: {error}</div>}
      {!loading && !error && (
        <pre className="text-sm overflow-auto">{JSON.stringify(result, null, 2)}</pre>
      )}
    </div>
  );
}
